---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
  namespace: dev
spec:
  selector:
    matchLabels:
      app: java
  replicas: 1
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: surekamani/java:3

---
apiVersion: v1
kind: Service
metadata:
  name: java
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32100
  selector:
    app: java
